---
####################
## Check spelling ##
####################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

name: Spell checking
#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Spell checking
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      #############################
      # Run check spelling action #
      #############################
      - name: Check spelling
        uses: check-spelling/check-spelling@main
        with:
          bucket: .github/actions
          project: spelling
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          


